name: CI
on: 
  pull_request:
    branches: [dev]
  push:
    branches: [dev]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "18.15.0"
      - run: npm ci
      - run: npm test -- --coverage
        env: 
          CI: true

      - name: Build App
        if: github.event_name == 'push'
        run: npm run build 
      - run: npm install -g surge
      - name: Deploy App to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain aboard-arithmetic.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}